#
# -- testtrigger,yml  - testing of event triggering
#
name: Test Release Trigger
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout GLE
        uses: actions/checkout@v4

      - name: Upload and Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/vlabella/GLE/releases/${{ github.event.workflow_run.id }}/assets
          asset_path: ./src/CMakeLists.txt
          asset_name: cmakelists
          asset_content_type: application/octet-stream
