#
# -- test calling trigger
#
name: test calling trigger
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: GLE Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: test-trigger
        client-payload: '{"upload_url": "foo", "tag": "bar"}'
    - name: GLE Library Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: test-trigger
        repository: vlabella/gle-library
        client-payload: '{"upload_url": "foo", "tag": "bar"}'
