#
# -- testtrigger,yml  - testing of event triggering
#
name: Test Release Trigger
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.id != '' }}
    steps:
      - name: Checkout GLE
        uses: actions/checkout@v4

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload and Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./src/src/CMakeLists.txt
          asset_name: cmakelists
          asset_content_type: application/octet-stream